#!/bin/env ruby

require_relative 'lib'
require_relative 'wikipedia'

# @param lineage [Array<Taxon>]
def format_lineage(lineage)
  lineage.map { |x| "#{x.rank_display}：#{x.display}" }.join("\n")
end

names = File.open('source.txt').read.lines(chomp: true).map { |x| x.split ' ' }.filter { |x| x.length == 2 }

out_file = 'lineage.txt'

File.delete out_file if File.exist? out_file
names.each do |tuple|
  puts "Fetching #{tuple[0]}..."
  page = "https://zh.wikipedia.org/wiki/Template:Taxonomy/#{tuple[1]}"
  lineage = fetch_full_lineage page
  # output = format_lineage lineage
  # output += "\n#{tuple[0]}"
  output = ''
  lineage.each do |taxon|
    output += "#{taxon.rank_display} #{taxon.display} #{taxon.sci_name}\n"
  end
  File.open(out_file, 'a+') do |f|
    f.write(output)
    f.write("\n")
  end
end
